# Configuration file for StatsPE

# Supported Languages:
# English (English) = eng,
# German (Deutsch) = deu
Language: eng
# Enable Stats: true/false
Stats:
  Online: true
  FirstJoin: true
  LastJoin: true
  JoinCount: true
  KillCount: true
  K/D: true
  DeathCount: true
  KickCount: true
  # OnlineTime has not been implemented
  OnlineTime: false
  BlockBreakCount: true
  BlockPlaceCount: true
  ChatCount: true
  FishCount: true
  BedEnterCount: true
  EatCount: true
  CraftCount: true
  DroppedItems: true

# Enable/Disable the Auto-Updater Feature.
Auto-Update: true
Shutdown-Message: "Restarting Server for update StatsPE plugin!"
# Time Format used for Stats like last and first Join
# Further information about this on this page:
# http://php.net/manual/de/function.date.php
# Default: "H:i:s d.m.Y" = Hour:Minute:Seconds Day.Month.Year
# Example: 12:00:63 22.07.2016
TimeFormat: "H:i:s d.m.Y"

# Set data provider for StatsPE
# Available Providers: MySQL, JSON
Provider: JSON

# MySQL Settings (Only configure this if you are going to use MySQL data provider)
MySQL:
  host: "MySQL.example.net:3306"
  user: "ExampleUser"
  password: "12345678"
  database: "StatsPE"
